baseURL = 'https://bydaytona.com/'
languageCode = 'en-us'
title = 'Daytona'
theme = "PaperMod"

enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
author = "daytona"
canonifyURLs = true
relativeURLs = false

[menu]

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20

[markup]
  [markup.highlight]
    style = "github"


